corrected bem class
ProtsyukPrits/project pull request #13
Opened 2022-05-28 08:41 UTC by Vlenster

2022-05-28 09:22 UTC, stgran66 commented on src/partials/contacts.html
> +         <div class="contacts__sity-wrap">
тут опечатка, розумію, що має бути city

2022-05-28 09:35 UTC, stgran66 requested changes
Напевно я би поправив кольори і використав змінні

2022-05-28 09:35 UTC, stgran66 commented on src/partials/contacts.html
> +     <li class="contacts__items">
Якщо тобі зручно так називати класи, то в сумі це має право на життя. Але item (в однині) є елементом list, а не contacts, якщо тобі це потрібно для стилізації, то ок, але я би додав його як елемени list, а ul дав би додатковий клас contacts-list, тоді li буде мати contacts-list__item

2022-05-28 09:35 UTC, stgran66 commented on src/partials/contacts.html
> +         <a href="" class="contacts__link"> noreply@envato.com</a>
на такого типу лінках треба ставити href відповідний, типу href="tel:+610383766284" href="mailto:noreply@envato.com". Це дасть можливість одразу відкрити потрібні апки

2022-05-28 09:35 UTC, stgran66 commented on src/sass/components/_contacts.scss
> +    display: block;
це не потрібно, це і так блок, і я би перевірив падинги, чи не задав їх вже Діма в спільних стилях (але тут не певен)

2022-05-28 09:35 UTC, stgran66 commented on src/sass/components/_contacts.scss
> +}
Аня зробила змінні на всі кольори і навіть бокс-шадоу в variables.scss. Краще їх використовувати

2022-05-28 13:58 UTC, ProtsyukPrits commented on src/partials/contacts.html
> +     <li class="contacts__items">
h2 class"contacts__title"

2022-05-28 16:43 UTC, Vlenster commented
Bem correct, upgrade semantics, +colors

2022-05-28 17:09 UTC, ProtsyukPrits approved these changes

2022-05-28 17:19 UTC, anyaShan requested changes

2022-05-28 17:19 UTC, anyaShan commented on src/partials/contacts.html
> +     <li class="contacts__card">
я б назвала contacts__item

2022-05-28 17:19 UTC, anyaShan commented on src/partials/contacts.html
> +         <div class="contacts__card-wrap">
Усі значення в sass перенести на li

2022-05-28 17:19 UTC, anyaShan commented on src/sass/components/_contacts.scss
> +    max-width: 280px;
задай значення width, а також задай це значення для media (max 480px), так як потім у тебе буде йти флекс із розрахунком ширини карточки

2022-05-28 17:19 UTC, anyaShan commented on src/sass/components/_contacts.scss
> +.contacts__card-wrap{
перенеси в li з класом .contacts__item

2022-05-28 17:19 UTC, anyaShan commented on src/sass/components/_contacts.scss
> +    margin-top: 24px;
краще задавати елементам margin-bottom, це кращий тон ведення css

2022-05-28 17:19 UTC, anyaShan commented on src/sass/components/_contacts.scss
> +    margin-top: 32px;
задай margin-botton до contacts__list

2022-05-28 17:19 UTC, anyaShan commented on src/sass/components/_contacts.scss
> +    margin-top: 20px;
тоді не знадобиться

2022-05-28 19:40 UTC, Vlenster commented
fixed

2022-05-28 19:47 UTC, ProtsyukPrits approved these changes

2022-05-28 19:50 UTC, ProtsyukPrits approved these changes

2022-05-28 21:14 UTC, Vlenster commented
Update_contacts css

2022-05-29 08:26 UTC, Vlenster commented
переробив

2022-05-29 12:03 UTC, ProtsyukPrits approved these changes

2022-05-29 12:04 UTC, merged