Feature/customer_tab v added
ProtsyukPrits/project pull request #42
Opened 2022-05-29 19:33 UTC by VolodymyrVelch

Додано таблет версію секції customer-reviews

2022-05-29 20:15 UTC, anyaShan requested changes

2022-05-29 20:15 UTC, anyaShan commented on src/sass/components/_customer-reviews.scss
> +    background: repeating-linear-gradient(#FAFAFA, #FAFAFA 30px, #E1E1E1 30px, #E1E1E1 31px);
Постав, будь ласка, змінні

2022-05-29 20:15 UTC, anyaShan commented on src/sass/components/_customer-reviews.scss
> +        background: repeating-linear-gradient(#fff, #fff 29px, #E1E1E1 29px, #E1E1E1 30px);
І тут теж змінні

2022-05-29 20:26 UTC, VolodymyrVelch commented on src/sass/components/_customer-reviews.scss
> +        background: repeating-linear-gradient(#fff, #fff 29px, #E1E1E1 29px, #E1E1E1 30px);
Змінну на 1 градієнт? Він  суто для версій mob, tab і desktop даної секції в інших місцях не заюзаєш так як прив'язка до line-height . Можу покласти, не ставив так як думав що змінні використовуємо коли елемент повторюється в проекті.

2022-05-30 14:40 UTC, stgran66 approved these changes

2022-05-30 14:56 UTC, merged